version: "3.4"

services:
  php:
    build:
      context: .
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: root
      DB_PASSWORD: supersecret
  nginx:
    image: nginx:1.17
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    image: "mysql:5"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: supersecret
